title: Leandra Fernandes - Profissional de Educação Física
email: leandralf@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leandrafernandes.com" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

permalink: /blog/:title/

paginate_path: '/blog/:num/'
pagination:
  enabled: true
  per_page: 12
  permalink: '/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true


include: ['_pages']

defaults:
  -
    scope:
      path:            "assets/*"
    values:
      sitemap:         false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
